{
	"version": 1504555601,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite2-sheet0.png",
		"images/correio-sheet0.png",
		"images/correio-sheet1.png",
		"images/correio-sheet2.png",
		"images/sprite3-sheet0.png",
		"images/carta2-sheet0.png",
		"images/carta2-sheet1.png",
		"images/amarelo-sheet0.png",
		"images/logo-sheet0.png",
		"images/nomelogo-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/playmenu-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"media/fim.m4a",
		"media/fim.ogg",
		"media/trilha sonora.m4a",
		"media/trilha sonora.ogg",
		"media/vitória.m4a",
		"media/vitória.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}